### ISSUE TITLE
Implement JSON API

### ISSUE THREAD

**Issue by nilshoerrmann** [pointybeard/api_framework#10]
_The title of this issue might sound a bit redundant because this is an extension that creates, uhm, a JSON API. What I'm referring to is http://jsonapi.org/._

I'm just digging into this extension, trying to understand what it does and how it works, but I immediately thought of the JSON API specification. From what I see in the readme, by default the extension just converts the Symphony data XML to JSON following a few rules – this makes a lot of sense in the context of Symphony where you usually handcraft your front-end interactions. 

But what about enabling Symphony to serve data to sites based on frameworks like [Ember](http://emberjs.com) that follow a strict data scheme as described in in the aforementioned specification?

If I understand the documentation correctly, transformers could be used to alter the result and thus they could be used to convert the output to the JSON API requirements. Would it be in the scope of this extension to offer such conversation out of the box?

**Comment by pointybeard** [comment]
Hey Nils. I am still trying to figure out exactly where this extension fits in the big scheme of things. It came about from a need to provide JSON data to an AngularJS frontend. It was difficult to do this with XSLT, at least in an elegant way, however converting from XML to JSON is trivial in PHP.

> But what about enabling Symphony to serve data to sites based on frameworks like Ember that follow a strict data scheme as described in in the aforementioned specification?

The problem here is that output is entirely dependent on how you construct the XML. Think of it like writing JSON in XML. The structure has to already exist in the XML to produce a particular JSON output. e.g.

```xml
<data>
    <id>10</id>
</data>
```

becomes

```json
{
    "id": 10
}
```

It's really up to you how you want your JSON to look. This extension and Symphony make no assumptions about what you're doing. If this was a "Entry to JSON API" data source thing, I could see that might work. But I deliberately coded this as an open ended XML to JSON renderer.

With regards to the transformers, I needed a way to subtly manipulate the behaviour of output depending on what I was doing, but I didn't want to alter the core features of the API framework extension to support whatever weird thing I happened to be doing. They might be able to achieve what you're suggesting, but they have no control over the XML that comes in.

With that said, there is boilerplate XSL which takes all the page XML (data sources, events and params) and just dumps it out. Coupled with a robust transformer, it might be possible to convert that XML into JSON API compliant output. The structure of the page XML is super consistent (with the exception of custom data sources and events).

```xml
<?xml version="1.0" encoding="UTF-8"?><xsl:stylesheet version="1.0"
 xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:template match="node()|@*">
      <xsl:copy>
        <xsl:apply-templates select="node()|@*"/>
      </xsl:copy>
    </xsl:template>
</xsl:stylesheet>
```

Currently the boiler plate XSL kicks in only if the page has a type of `JSON` and there is a GET variable `boilerplate-xsl`. There might be other ways to trigger this though. Also, now that `?debug` works correctly, there isn't a need for this GET variable anymore (mental note to remove it).

I would be interested in discussing all of this further. I suspect it might be slightly out of scope, but worth talking through nonetheless.

**Comment by nilshoerrmann** [comment]
Thanks for this reasoned response.

> It's really up to you how you want your JSON to look. This extension and Symphony make no assumptions about what you're doing. If this was a "Entry to JSON API" data source thing, I could see that might work. But I deliberately coded this as an open ended XML to JSON renderer.

That's a really good point and I think this is exactly I like about your approach to this extension.

I'll think a bit more about how an automated conversion from Symphony output to the JSON API might be possible and will post back here (I actually think it shouldn't be that hard).
